[package]
name = "rust-2021-12-23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
dropshot = "0.6.0"
tokio = { version = "1.15.0", features = ["full"] }
