[package]
name = "rust-2021-07-31"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["other", "ioutil", "time"] }
anyhow = "1.0.42"

